using System.Text.Json.Serialization;

namespace AiUtility.GeminiUtilityServices.Models;

/// <summary>
/// Represents a response returned by the Gemini GenerateContent API.
/// </summary>
public class GeminiResponse
{
    /// <summary>
    /// Gets or sets candidate responses generated by Gemini.
    /// </summary>
    [JsonPropertyName("candidates")]
    public List<GeminiCandidate> Candidates { get; set; } = [];

    /// <summary>
    /// Gets or sets feedback associated with the submitted prompt.
    /// </summary>
    [JsonPropertyName("promptFeedback")]
    public GeminiPromptFeedback? PromptFeedback { get; set; }

    /// <summary>
    /// Gets or sets token usage metadata returned by Gemini.
    /// </summary>
    [JsonPropertyName("usageMetadata")]
    public GeminiUsageMetadata? UsageMetadata { get; set; }

    /// <summary>
    /// Gets or sets the Gemini model version that generated this response.
    /// </summary>
    [JsonPropertyName("modelVersion")]
    public string? ModelVersion { get; set; }

    /// <summary>
    /// Gets or sets the unique identifier assigned to this Gemini response.
    /// </summary>
    [JsonPropertyName("responseId")]
    public string? ResponseId { get; set; }

    /// <summary>
    /// Gets or sets status information for the model used by the response.
    /// </summary>
    [JsonPropertyName("modelStatus")]
    public GeminiModelStatus? ModelStatus { get; set; }

    /// <summary>
    /// Gets the first content part from the first candidate.
    /// </summary>
    [JsonIgnore]
    public GeminiPart? FirstPart =>
        Candidates
            .FirstOrDefault()?
            .Content?
            .Parts?
            .OfType<GeminiPart>()
            .FirstOrDefault();

    /// <summary>
    /// Gets the text contained in the first Gemini response part.
    /// </summary>
    [JsonIgnore]
    public string Text =>
        FirstPart?.Text ?? string.Empty;

    /// <summary>
    /// Gets a read-only view of the text contained in the first response part.
    /// </summary>
    [JsonIgnore]
    public ReadOnlyMemory<char> RawText =>
        FirstPart?.RawText
        ?? ReadOnlyMemory<char>.Empty;

    /// <summary>
    /// Gets the function call contained in the first response part.
    /// </summary>
    [JsonIgnore]
    public GeminiFunctionCall? FunctionCall =>
        FirstPart?.FunctionCall;

    /// <summary>
    /// Creates a deep copy of the current Gemini response.
    /// </summary>
    /// <returns>
    /// A new <see cref="GeminiResponse"/> containing independent mutable child objects.
    /// </returns>
    public GeminiResponse DeepClone()
    {
        return new GeminiResponse
        {
            Candidates = Candidates
                .Select(static candidate => candidate.DeepClone())
                .ToList(),

            UsageMetadata = UsageMetadata?.DeepCopy(),

            ModelVersion = ModelVersion,

            ResponseId = ResponseId
        };
    }
}